import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart';
import 'models/flashcard_model.dart';
import 'models/quiz_result_model.dart';
import 'providers/theme_provider.dart';
import 'providers/flashcard_provider.dart';
import 'providers/quiz_provider.dart';
import 'providers/auth_provider.dart';
import 'utils/constants.dart';
import 'utils/app_theme.dart';
import 'screens/splash_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize Hive local database
  await Hive.initFlutter();

  // Register Hive adapters (generated by build_runner)
 // Hive.registerAdapter(FlashcardModelAdapter());
  //Hive.registerAdapter(QuizResultModelAdapter());

  // Open Hive boxes
  await Hive.openBox<FlashcardModel>(AppConstants.flashcardBox);
  await Hive.openBox<QuizResultModel>(AppConstants.quizHistoryBox);
  await Hive.openBox(AppConstants.settingsBox);

  runApp(const FlashMasterApp());
}

class FlashMasterApp extends StatelessWidget {
  const FlashMasterApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => FlashcardProvider()),
        ChangeNotifierProvider(create: (_) => QuizProvider()),
      ],
      child: Consumer<ThemeProvider>(
        builder: (context, themeProvider, _) {
          return MaterialApp(
            title: AppConstants.appName,
            debugShowCheckedModeBanner: false,
            theme: AppTheme.lightTheme,
            darkTheme: AppTheme.darkTheme,
            themeMode: themeProvider.themeMode,
            home: const SplashScreen(),
          );
        },
      ),
    );
  }
}